name: Build and Deploy POAM AI Assistant

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/poam-ai-assistant:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/poam-ai-assistant:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
           script: |
              sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/poam-ai-assistant:latest
              sudo docker stop poam-ai-assistant || true
              sudo docker rm poam-ai-assistant || true
              sudo docker run -d --name poam-ai-assistant --restart always -p 8501:8501 ${{ secrets.DOCKERHUB_USERNAME }}/poam-ai-assistant:latest